version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-miniorootuser}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-miniorootpassword}
    volumes:
      - E:\Works\MinIO:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
